### PR TITLE
Build htslib 1.20

### PR DESCRIPTION
**Pull request by jdblischak**
https://github.com/TileDB-Inc/m2w64-htslib-build/releases/tag/1.20-0

xref: https://github.com/TileDB-Inc/m2w64-htslib-build/pull/10, https://github.com/TileDB-Inc/m2w64-htslib-build/pull/8

### CODE REVIEW

**Review by teo-tsirpanis — APPROVED** [review]

**Comment by jdblischak** [comment]
No [binary](https://anaconda.org/tiledb/m2w64-htslib/files) was uploaded because the [upload staged failed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=40293&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc). I suspect the Anaconda token needs to be rotated. Specifically the Azure pipeline variable `BINSTAR_TOKEN` at https://dev.azure.com/TileDB-Inc/CI/_build?definitionId=46. 

Edit -> Variables -> BINSTAR_TOKEN -> copy-paste new token in Value -> OK

**Comment by teo-tsirpanis** [comment]
@ihnorton could you do that?

**Comment by ihnorton** [comment]
Done

**Comment by teo-tsirpanis** [comment]
Thanks. Reran CI.

**Pull request merged**
